version: 0.2
env:
  parameter-store:
    DOCKERHUB_TOKEN: /dockerhub/token
    DOCKERHUB_USER: /dockerhub/user
phases:
  pre_build:
    commands:
      - echo ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUB_USER} --password-stdin
  build:
    commands:
      - docker build -t reactapp:latest .
  post_build:
    commands:
      - docker tag reactapp:latest ${DOCKERHUB_USER}/reactapp:latest
      - docker push ${DOCKERHUB_USER}/reactapp:latest
