name: Deployment Exercise 1
on: push
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
        continue-on-error: true

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          browser: chrome
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Upload test report artifact
        if: always() # Ensure this step runs even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-report
          path: /home/runner/work/RoboFiends/RoboFiends/cypress/reports/html/.jsons/mochawesome.json

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build code
        run: npm run build

      - name: Deploy code
        run: echo "Deploying..."
